name: "arian-Fx"

exports: "Fx.js"

description: "Other Fx implementation for MooTools"

license: "[MIT License](http://mootools.net/license.txt)"

authors: "Arian Stolwijk"

sources:
  - "Source/Fx/Fx.js"
  - "Source/Fx/Fx.Morph.js"
  - "Source/Fx/Fx.Equations.js"

