name: "Drag"

exports: "Drag.js"

description: "Another Drag implementation for MooTools"

license: "[MIT License](http://mootools.net/license.txt)"

authors: "Arian Stolwijk"

sources:
  - "Source/Drag.js"
  - "Source/Drag.Move.js"
  - "Source/Drag.Drop.js"

